### ISSUE TITLE
GPU architecture issue

### ISSUE THREAD

**Issue by gokulnandan-0** [OSU-NLP-Group/HippoRAG#22]
Process Process-2:
Traceback (most recent call last):
  File "/home/gokul/miniconda3/envs/hipporag/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 1900, in _run_ninja_build
    subprocess.run(
  File "/home/gokul/miniconda3/envs/hipporag/lib/python3.9/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/gokul/miniconda3/envs/hipporag/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/gokul/miniconda3/envs/hipporag/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/gokul/miniconda3/envs/hipporag/lib/python3.9/site-packages/colbert/infra/launcher.py", line 134, in setup_new_process
    return_val = callee(config, *args)
  File "/home/gokul/miniconda3/envs/hipporag/lib/python3.9/site-packages/colbert/indexing/collection_indexer.py", line 33, in encode
    encoder.run(shared_lists)
  File "/home/gokul/miniconda3/envs/hipporag/lib/python3.9/site-packages/colbert/indexing/collection_indexer.py", line 68, in run
    self.train(shared_lists) # Trains centroids from selected passages
  File "/home/gokul/miniconda3/envs/hipporag/lib/python3.9/site-packages/colbert/indexing/collection_indexer.py", line 237, in train
    bucket_cutoffs, bucket_weights, avg_residual = self._compute_avg_residual(centroids, heldout)
  File "/home/gokul/miniconda3/envs/hipporag/lib/python3.9/site-packages/colbert/indexing/collection_indexer.py", line 315, in _compute_avg_residual
    compressor = ResidualCodec(config=self.config, centroids=centroids, avg_residual=None)
  File "/home/gokul/miniconda3/envs/hipporag/lib/python3.9/site-packages/colbert/indexing/codecs/residual.py", line 24, in __init__
    ResidualCodec.try_load_torch_extensions(self.use_gpu)
  File "/home/gokul/miniconda3/envs/hipporag/lib/python3.9/site-packages/colbert/indexing/codecs/residual.py", line 103, in try_load_torch_extensions
    decompress_residuals_cpp = load(
  File "/home/gokul/miniconda3/envs/hipporag/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 1284, in load
    return _jit_compile(
  File "/home/gokul/miniconda3/envs/hipporag/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 1508, in _jit_compile
    _write_ninja_file_and_build_library(
  File "/home/gokul/miniconda3/envs/hipporag/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 1623, in _write_ninja_file_and_build_library
    _run_ninja_build(
  File "/home/gokul/miniconda3/envs/hipporag/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 1916, in _run_ninja_build
    raise RuntimeError(message) from e
RuntimeError: Error building extension 'decompress_residuals_cpp': [1/2] /usr/bin/nvcc  -DTORCH_EXTENSION_NAME=decompress_residuals_cpp -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -isystem /home/gokul/miniconda3/envs/hipporag/lib/python3.9/site-packages/torch/include -isystem /home/gokul/miniconda3/envs/hipporag/lib/python3.9/site-packages/torch/include/torch/csrc/api/include -isystem /home/gokul/miniconda3/envs/hipporag/lib/python3.9/site-packages/torch/include/TH -isystem /home/gokul/miniconda3/envs/hipporag/lib/python3.9/site-packages/torch/include/THC -isystem /home/gokul/miniconda3/envs/hipporag/include/python3.9 -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -gencode=arch=compute_75,code=compute_75 -gencode=arch=compute_75,code=sm_75 --compiler-options '-fPIC' -std=c++14 -c /home/gokul/miniconda3/envs/hipporag/lib/python3.9/site-packages/colbert/indexing/codecs/decompress_residuals.cu -o decompress_residuals.cuda.o 
FAILED: decompress_residuals.cuda.o 
/usr/bin/nvcc  -DTORCH_EXTENSION_NAME=decompress_residuals_cpp -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -isystem /home/gokul/miniconda3/envs/hipporag/lib/python3.9/site-packages/torch/include -isystem /home/gokul/miniconda3/envs/hipporag/lib/python3.9/site-packages/torch/include/torch/csrc/api/include -isystem /home/gokul/miniconda3/envs/hipporag/lib/python3.9/site-packages/torch/include/TH -isystem /home/gokul/miniconda3/envs/hipporag/lib/python3.9/site-packages/torch/include/THC -isystem /home/gokul/miniconda3/envs/hipporag/include/python3.9 -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -gencode=arch=compute_75,code=compute_75 -gencode=arch=compute_75,code=sm_75 --compiler-options '-fPIC' -std=c++14 -c /home/gokul/miniconda3/envs/hipporag/lib/python3.9/site-packages/colbert/indexing/codecs/decompress_residuals.cu -o decompress_residuals.cuda.o 
nvcc fatal   : Unsupported gpu architecture 'compute_75'
ninja: build stopped: subcommand failed.

**Comment by yhshu** [comment]
Hello, I think this is an error caused by ninja not being found by a subprocess. 
You can try to add the bin dir of the hipporag conda environment to the environment variable:
```
export PATH=$PATH:/your_path/HippoRAG/hipporag/bin
```
where `/your_path/HippoRAG` is the project root, `/your_path/HippoRAG/hipporag` is the conda env path.

**Comment by gokulnandan-0** [comment]
That did not fix the problem. The core issue seems to related to ninja itself, cause there is no Cmake file to build the ninja,

**Comment by yhshu** [comment]
Because of this:
```
raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.
```

So first, could you find ninja using your terminal?
Additionally, the subprocess that tries to find ninja requires the environment variable to find ninja. That is mentioned in my last comment.
And please make sure to follow `requirements.txt` to install the whole environments, where ninja is included.

**Comment by gokulnandan-0** [comment]
pip show ninja
Name: ninja
Version: 1.11.1.1
Summary: Ninja is a small build system with a focus on speed
Home-page: http://ninja-build.org/
Author: Jean-Christophe Fillion-Robin
Author-email: scikit-build@googlegroups.com
License: Apache 2.0
Location: /home/gokul/miniconda3/envs/hipporag/lib/python3.9/site-packages
Requires: 
Required-by: colbert-ai
(hipporag) gokul@Gokultm-D:~/Desktop/HippoRAG$ ninja -v
ninja: error: loading 'build.ninja': No such file or directory

**Comment by yhshu** [comment]
So I don't think this is about Cmake building Ninja, but it's an environment variable configuration issue. Since you're using miniconda and not conda, I'm not sure if the settings are consistent, but maybe you want to consider adding `/home/gokul/miniconda3/envs/hipporag/bin` to the `PATH`.

**Comment by gokulnandan-0** [comment]
The miniconda env path is already part of the PATH variable

**Comment by 66246764** [comment]
have you solved this prombles？i got the same problmes，and i have adding my envs to path. but it not work

**Comment by yhshu** [comment]
Overall, I highly recommend using conda to run this repo instead of miniconda. @gokulnandan-0
