### ISSUE TITLE
I can't use ollama's model

### ISSUE THREAD

**Issue by aJarOfCode** [OSU-NLP-Group/HippoRAG#53]
The documentation says you can use langchain's model options
I changed the code in the example src/test_hipporag.py
the
hipporag = HippoRAG(args.dataset, 'openai', args.extraction_model, args.retrieval_model,  doc_ensemble=args.doc_ensemble, dpr_only=args.dpr_only,
qa_model=LangChainModel('openai', 'gpt-3.5-turbo'))
I changed it to
hipporag = HippoRAG(args.dataset, 'ollama', args.extraction_model, args.retrieval_model,  doc_ensemble=args.doc_ensemble, dpr_only=args.dpr_only,
qa_model=LangChainModel('ollama', 'llama3'))
When I run python src/test_hipporag.py --dataset hotpotqa --extraction_model llama3 --retrieval_model colbertv2 in the terminal, it returns:

/ home/ajarofcode/anaconda3 / envs/hipporag/lib/python3.9 / site - packages/torch/cuda/set py: 497: UserWarning: Can't initialize NVML
warnings.warn("Can't initialize NVML")
2024-09-07 10:00:14,440 - hipporag - CRITICAL - No extraction files found: output/openie_hotpotqa_results_ner_llama3_*.json ;  please check if working directory is correct or if the extraction has been done.
Traceback (most recent call last):
File "/home/ajarofcode/HippoRAG/src/test_hipporag.py", line 26, in <module>
hipporag = HippoRAG(args.dataset, 'ollama', args.extraction_model, args.retrieval_model,  doc_ensemble=args.doc_ensemble, dpr_only=args.dpr_only,
File "/home/ajarofcode/HippoRAG/src/hipporag.py", line 107, in __init__
self.build_graph()
File "/home/ajarofcode/HippoRAG/src/hipporag.py", line 450, in build_graph
for edge, weight in tqdm(self.graph_plus.items(), total=len(self.graph_plus), desc='Building Graph'):
AttributeError: 'HippoRAG' object has no attribute 'graph_plus'
What should I do, please?

**Comment by yhshu** [comment]
Hello,
I think you need to check your cuda environment, because I see:
```
/ home/ajarofcode/anaconda3 / envs/hipporag/lib/python3.9 / site - packages/torch/cuda/set py: 497: UserWarning: Can't initialize NVML
warnings.warn("Can't initialize NVML")
```

This is an Ollama issue rather than HippoRAG. Subsequent execution is not possible because of indexing failures.

**Comment by aJarOfCode** [comment]
Thank you very much for your reply. Since my computer is a windows operating system, I can only use a Linux virtual machine, so I had a small problem installing the drivers. I really want HippoRAG to be multi-platform.
      I wish you a happy life.
________________________________
发件人: Yiheng Shu ***@***.***>
发送时间: 2024年9月7日 20:47
收件人: OSU-NLP-Group/HippoRAG ***@***.***>
抄送: Ajarofcode ***@***.***>; Author ***@***.***>
主题: Re: [OSU-NLP-Group/HippoRAG] I can't use ollama's model (Issue #53)


Hello,
I think you need to check your cuda environment, because I see:

/ home/ajarofcode/anaconda3 / envs/hipporag/lib/python3.9 / site - packages/torch/cuda/set py: 497: UserWarning: Can't initialize NVML
warnings.warn("Can't initialize NVML")


This is an Ollama issue rather than HippoRAG. Subsequent execution is not possible because of indexing failures.
